// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class Env {
  static const String serverUrl = 'http://10.0.2.2:3001';
  static const String graphQlEndPoint = '$serverUrl/graphql';

  static FirebaseOptions get firebaseConfig {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ1F5GiMowOi4Ep9aZP2eGFAgatVER6Qk',
    appId: '1:1093217173324:web:5a40ce1b8aab4d61ea99e9',
    messagingSenderId: '1093217173324',
    projectId: 'taskifie',
    authDomain: 'taskifie.firebaseapp.com',
    storageBucket: 'taskifie.appspot.com',
    measurementId: 'G-CWBMV0EB8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQHzGyTvtF76HJcXnXcjPraHFLw4MSpUI',
    appId: '1:1093217173324:android:27d9732bc631774dea99e9',
    messagingSenderId: '1093217173324',
    projectId: 'taskifie',
    storageBucket: 'taskifie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBywcDKSZQp9FJP3rkLp2qMuzRuS-X8uKg',
    appId: '1:1093217173324:ios:0d762039577c6d00ea99e9',
    messagingSenderId: '1093217173324',
    projectId: 'taskifie',
    storageBucket: 'taskifie.appspot.com',
    iosBundleId: 'com.example.taskifie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBywcDKSZQp9FJP3rkLp2qMuzRuS-X8uKg',
    appId: '1:1093217173324:ios:83058d0d12ba2d13ea99e9',
    messagingSenderId: '1093217173324',
    projectId: 'taskifie',
    storageBucket: 'taskifie.appspot.com',
    iosBundleId: 'com.example.taskifie.RunnerTests',
  );
}
